# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
     # - name: commit_ref_to_footer TOdo finish 
      #  uses: https://docs.github.com/en/actions/learn-github-actions/variables#passing-values-between-steps-and-jobs-in-a-workflow
    #https://docs.github.com/en/actions/learn-github-actions/variables#passing-values-between-steps-and-jobs-in-a-workflow
       # env: 
          # gets commit
          # GITHUB_REF_NAME
        - name: checkout
          uses: actions/checkout@v4

        - name: Declare some variables
          shell: bash
          run: |
           echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
           echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
  
        - name: Another step
          run: |
           echo "Branch: ${{ env.branch }}"
           echo "Sha: ${{ env.sha_short }}"

        - name: write_commit
          uses: DamianReeves/write-file-action@v1.3
          with: 
            path: templates/commit.html
            write-mode: overwrite
            contents: ${{ env.sha_short }}


        - name: build_and_deploy
          uses: shalzz/zola-deploy-action@v0.17.2
          env:
           # Target branch
            PAGES_BRANCH: gh-pages
            # Provide personal access token
            TOKEN: ${{ secrets.GITHUB_TOKEN }}